import java.util.ArrayList;
import java.util.List;

public class CardTest {
    private static void typeTest() {
        System.out.println("----------------------------------单排----------------------------------");
        System.out.println(CardsFactory.builder("3"));
        System.out.println(CardsFactory.builder("4"));
        System.out.println(CardsFactory.builder("5"));
        System.out.println(CardsFactory.builder("6"));
        System.out.println(CardsFactory.builder("7"));
        System.out.println(CardsFactory.builder("8"));
        System.out.println(CardsFactory.builder("9"));
        System.out.println(CardsFactory.builder("0"));
        System.out.println(CardsFactory.builder("J"));
        System.out.println(CardsFactory.builder("Q"));
        System.out.println(CardsFactory.builder("K"));
        System.out.println(CardsFactory.builder("A"));
        System.out.println(CardsFactory.builder("2"));
        System.out.println(CardsFactory.builder("C"));
        System.out.println("----------------------------------对子----------------------------------");
        System.out.println(CardsFactory.builder("33"));
        System.out.println(CardsFactory.builder("44"));
        System.out.println(CardsFactory.builder("55"));
        System.out.println(CardsFactory.builder("66"));
        System.out.println(CardsFactory.builder("77"));
        System.out.println(CardsFactory.builder("88"));
        System.out.println(CardsFactory.builder("99"));
        System.out.println(CardsFactory.builder("00"));
        System.out.println(CardsFactory.builder("JJ"));
        System.out.println(CardsFactory.builder("QQ"));
        System.out.println(CardsFactory.builder("KK"));
        System.out.println(CardsFactory.builder("AA"));
        System.out.println(CardsFactory.builder("22"));
        System.out.println(CardsFactory.builder("CC") + " 炸弹");
        System.out.println("----------------------------------3个----------------------------------");
        System.out.println(CardsFactory.builder("333"));
        System.out.println(CardsFactory.builder("444"));
        System.out.println(CardsFactory.builder("555"));
        System.out.println(CardsFactory.builder("666"));
        System.out.println(CardsFactory.builder("777"));
        System.out.println(CardsFactory.builder("888"));
        System.out.println(CardsFactory.builder("999"));
        System.out.println(CardsFactory.builder("000"));
        System.out.println(CardsFactory.builder("JJJ"));
        System.out.println(CardsFactory.builder("QQQ"));
        System.out.println(CardsFactory.builder("KKK"));
        System.out.println(CardsFactory.builder("AAA"));
        System.out.println(CardsFactory.builder("222"));
        System.out.println(CardsFactory.builder("CCC") + " 炸弹");
        System.out.println("----------------------------------4个----------------------------------");
        System.out.println(CardsFactory.builder("3333"));
        System.out.println(CardsFactory.builder("4444"));
        System.out.println(CardsFactory.builder("5555"));
        System.out.println(CardsFactory.builder("6666"));
        System.out.println(CardsFactory.builder("7777"));
        System.out.println(CardsFactory.builder("8888"));
        System.out.println(CardsFactory.builder("9999"));
        System.out.println(CardsFactory.builder("0000"));
        System.out.println(CardsFactory.builder("JJJJ"));
        System.out.println(CardsFactory.builder("QQQQ"));
        System.out.println(CardsFactory.builder("KKKK"));
        System.out.println(CardsFactory.builder("AAAA"));
        System.out.println(CardsFactory.builder("2222"));
        System.out.println(CardsFactory.builder("CCCC"));
        System.out.println("----------------------------------5个----------------------------------");
        System.out.println(CardsFactory.builder("33333"));
        System.out.println(CardsFactory.builder("44444"));
        System.out.println(CardsFactory.builder("55555"));
        System.out.println(CardsFactory.builder("66666"));
        System.out.println(CardsFactory.builder("77777"));
        System.out.println(CardsFactory.builder("88888"));
        System.out.println(CardsFactory.builder("99999"));
        System.out.println(CardsFactory.builder("00000"));
        System.out.println(CardsFactory.builder("JJJJJ"));
        System.out.println(CardsFactory.builder("QQQQQ"));
        System.out.println(CardsFactory.builder("KKKKK"));
        System.out.println(CardsFactory.builder("AAAAA"));
        System.out.println(CardsFactory.builder("22222"));
        System.out.println(CardsFactory.builder("CCCCC"));
        System.out.println("----------------------------------6个----------------------------------");
        System.out.println(CardsFactory.builder("333333"));
        System.out.println(CardsFactory.builder("444444"));
        System.out.println(CardsFactory.builder("555555"));
        System.out.println(CardsFactory.builder("666666"));
        System.out.println(CardsFactory.builder("777777"));
        System.out.println(CardsFactory.builder("888888"));
        System.out.println(CardsFactory.builder("999999"));
        System.out.println(CardsFactory.builder("000000"));
        System.out.println(CardsFactory.builder("JJJJJJ"));
        System.out.println(CardsFactory.builder("QQQQQQ"));
        System.out.println(CardsFactory.builder("KKKKKK"));
        System.out.println(CardsFactory.builder("AAAAAA"));
        System.out.println(CardsFactory.builder("222222"));
        System.out.println(CardsFactory.builder("CCCCCC"));
        System.out.println("----------------------------------7个----------------------------------");
        System.out.println(CardsFactory.builder("3333333"));
        System.out.println(CardsFactory.builder("4444444"));
        System.out.println(CardsFactory.builder("5555555"));
        System.out.println(CardsFactory.builder("6666666"));
        System.out.println(CardsFactory.builder("7777777"));
        System.out.println(CardsFactory.builder("8888888"));
        System.out.println(CardsFactory.builder("9999999"));
        System.out.println(CardsFactory.builder("0000000"));
        System.out.println(CardsFactory.builder("JJJJJJJ"));
        System.out.println(CardsFactory.builder("QQQQQQQ"));
        System.out.println(CardsFactory.builder("KKKKKKK"));
        System.out.println(CardsFactory.builder("AAAAAAA"));
        System.out.println(CardsFactory.builder("2222222"));
        System.out.println(CardsFactory.builder("CCCCCCC"));
        System.out.println("----------------------------------8个----------------------------------");
        System.out.println(CardsFactory.builder("33333333"));
        System.out.println(CardsFactory.builder("44444444"));
        System.out.println(CardsFactory.builder("55555555"));
        System.out.println(CardsFactory.builder("66666666"));
        System.out.println(CardsFactory.builder("77777777"));
        System.out.println(CardsFactory.builder("88888888"));
        System.out.println(CardsFactory.builder("99999999"));
        System.out.println(CardsFactory.builder("00000000"));
        System.out.println(CardsFactory.builder("JJJJJJJJ"));
        System.out.println(CardsFactory.builder("QQQQQQQQ"));
        System.out.println(CardsFactory.builder("KKKKKKKK"));
        System.out.println(CardsFactory.builder("AAAAAAAA"));
        System.out.println(CardsFactory.builder("22222222"));
        System.out.println(CardsFactory.builder("CCCCCCCC"));
        System.out.println("----------------------------------三带一----------------------------------");
        System.out.println(CardsFactory.builder("3331"));
        System.out.println(CardsFactory.builder("4442"));
        System.out.println(CardsFactory.builder("5553"));
        System.out.println(CardsFactory.builder("6664"));
        System.out.println(CardsFactory.builder("7775"));
        System.out.println(CardsFactory.builder("8886"));
        System.out.println(CardsFactory.builder("9997"));
        System.out.println(CardsFactory.builder("0008"));
        System.out.println(CardsFactory.builder("JJJ9"));
        System.out.println(CardsFactory.builder("QQQ0"));
        System.out.println(CardsFactory.builder("KKKJ"));
        System.out.println(CardsFactory.builder("AAAQ"));
        System.out.println(CardsFactory.builder("222K"));
        System.out.println(CardsFactory.builder("CCC1") + " 错误");
        System.out.println("----------------------------------三带一对----------------------------------");
        System.out.println(CardsFactory.builder("33311"));
        System.out.println(CardsFactory.builder("44422"));
        System.out.println(CardsFactory.builder("55533"));
        System.out.println(CardsFactory.builder("66644"));
        System.out.println(CardsFactory.builder("77755"));
        System.out.println(CardsFactory.builder("88866"));
        System.out.println(CardsFactory.builder("99977"));
        System.out.println(CardsFactory.builder("00088"));
        System.out.println(CardsFactory.builder("JJJ99"));
        System.out.println(CardsFactory.builder("QQQ00"));
        System.out.println(CardsFactory.builder("KKKJJ"));
        System.out.println(CardsFactory.builder("AAAQQ"));
        System.out.println(CardsFactory.builder("222KK"));
        System.out.println(CardsFactory.builder("CCC11") + " 错误");
        System.out.println(CardsFactory.builder("JcJCJ") + " 不能带对王");
        System.out.println(CardsFactory.builder("222K1") + " 不是对子");
        System.out.println("----------------------------------四带二----------------------------------");
        System.out.println(CardsFactory.builder("444412"));
        System.out.println(CardsFactory.builder("444466"));
        System.out.println(CardsFactory.builder("444445"));
        System.out.println(CardsFactory.builder("4444Cc"));
        System.out.println("----------------------------------四带两对----------------------------------");
        System.out.println(CardsFactory.builder("44441122"));
        System.out.println(CardsFactory.builder("44446666"));
        System.out.println(CardsFactory.builder("44444455"));
        System.out.println(CardsFactory.builder("444466Cc"));
        System.out.println(CardsFactory.builder("4444Cc33"));
        System.out.println("----------------------------------顺子----------------------------------");
        System.out.println(CardsFactory.builder("34567"));
        System.out.println("----------------------------------连对----------------------------------");
        System.out.println(CardsFactory.builder("334455"));
        System.out.println("----------------------------------飞机----------------------------------");
        System.out.println(CardsFactory.builder("333444"));
        System.out.println("----------------------------------飞机带单排----------------------------------");
        System.out.println(CardsFactory.builder("33 555666777 7"));
        System.out.println(CardsFactory.builder("333444555666"));
        System.out.println(CardsFactory.builder("33334444") + "飞机/四带两对");
        System.out.println(CardsFactory.builder("33334445"));
        System.out.println(CardsFactory.builder("33344445"));
        System.out.println(CardsFactory.builder("33344455"));
        System.out.println(CardsFactory.builder("33344456"));
        System.out.println(CardsFactory.builder("333444555777"));
        System.out.println(CardsFactory.builder("333555666777"));
        System.out.println(CardsFactory.builder("222555666777"));
        System.out.println(CardsFactory.builder("333444555444"));
        System.out.println(CardsFactory.builder("222111KKKQQQ"));
        System.out.println(CardsFactory.builder("333444555666"));
        System.out.println(CardsFactory.builder("333 555 666 777 888 999 000 JJJ"));
        System.out.println(CardsFactory.builder("333 555 666 777 888 999 000 QQQ"));
        System.out.println(CardsFactory.builder("633 555 666 777 888 999 000 QQQ"));
        System.out.println(CardsFactory.builder("333 444 666 777 888 999 000 JJJ"));
        System.out.println(CardsFactory.builder("JJJ 000 888 777 666 555 444 333"));
        System.out.println(CardsFactory.builder("222AAAKKK JJJ000999888777666555444333"));
        System.out.println(CardsFactory.builder("333 444 555 666 777 888 999 000 JJJ QQQ KKK AAA"));
        System.out.println("---------------------------------飞机带对子---------------------------------");
        System.out.println(CardsFactory.builder("334445556667777") + " 头切");
        System.out.println(CardsFactory.builder("334444555666777") + " 尾切");
        System.out.println(CardsFactory.builder("334455 555666777"));
        System.out.println(CardsFactory.builder("384455 555666777") + " 错误");
        System.out.println(CardsFactory.builder("33334444455566677777") + " 飞机带单双");
        System.out.println(CardsFactory.builder("444555666777888999 9447733") + " 飞机带单双");
        System.out.println(CardsFactory.builder("33334444 555666777888"));
        System.out.println(CardsFactory.builder("33334444 666777888999"));
        System.out.println(CardsFactory.builder("333444555666 88889999"));
        System.out.println(CardsFactory.builder("3333344455"));
        System.out.println(CardsFactory.builder("3334444455"));
        System.out.println(CardsFactory.builder("3344444555"));
    }

    private static void outCardTest() {
        //TODO 55554444压44445566和33334445
        //TODO 444555666777 压 333444555777
        System.out.println("---------------------------------成功区 下面不能出现-1---------------------------------");
        System.out.println(CardsFactory.builder("C").isGreaterThan(CardsFactory.builder("c").list.get(0)));
        System.out.println(CardsFactory.builder("C").isGreaterThan(CardsFactory.builder("2").list.get(0)));
        System.out.println(CardsFactory.builder("c").isGreaterThan(CardsFactory.builder("1").list.get(0)));
        System.out.println(CardsFactory.builder("77").isGreaterThan(CardsFactory.builder("66").list.get(0)));
        System.out.println(CardsFactory.builder("CC").isGreaterThan(CardsFactory.builder("Cc").list.get(0)));
        System.out.println(CardsFactory.builder("Cc").isGreaterThan(CardsFactory.builder("cc").list.get(0)));
        System.out.println(CardsFactory.builder("CC").isGreaterThan(CardsFactory.builder("cc").list.get(0)));

        System.out.println(CardsFactory.builder("55554444").isGreaterThan(CardsFactory.builder("44445656").list.get(0)));
        System.out.println(CardsFactory.builder("55554444").isGreaterThan(CardsFactory.builder("33334445").list.get(0)));
        System.out.println(CardsFactory.builder("444555666777").isGreaterThan(CardsFactory.builder("333444555777").list.get(0)));
        System.out.println("---------------------------------失败区 下面只能出现-1---------------------------------");
        //黑桃6压方块6测试
        Card card4 = new Card(GameConstants.ID_6_4);
        Card card1 = new Card(GameConstants.ID_6_1);
        List<Card> list1 = new ArrayList<>();
        list1.add(card4);
        List<Card> list2 = new ArrayList<>();
        list2.add(card1);
        System.out.println(CardsFactory.builder(list1).isGreaterThan(CardsFactory.builder(list2).list.get(0)));
        System.out.println(CardsFactory.builder(list2).isGreaterThan(CardsFactory.builder(list1).list.get(0)));
        System.out.println(CardsFactory.builder("6").isGreaterThan(CardsFactory.builder("6").list.get(0)));
        System.out.println(CardsFactory.builder("66").isGreaterThan(CardsFactory.builder("66").list.get(0)));
        System.out.println(CardsFactory.builder("Cc").isGreaterThan(CardsFactory.builder("cC").list.get(0)));
    }

    private static void prompt() {
        System.out.println("----------------------------------单牌----------------------------------");
        //单独提示 小王大王 优先提示单牌 出小王提示大王
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA2cC"), CardsFactory.builder("5").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("3300JQQKA22Cc"), CardsFactory.builder("5").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("Cc2k6"), CardsFactory.builder("A").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("Cc654"), CardsFactory.builder("c").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("Cc654"), CardsFactory.builder("C").list.get(0)));
        System.out.println("----------------------------------对子----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("3344556677889900JJQQKKA22ccCC"), CardsFactory.builder("55").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("8888000JJQQQKKKKAA222cCC"), CardsFactory.builder("55").list.get(0)));
        System.out.println("----------------------------------三个----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("77788899"), CardsFactory.builder("888").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("777888999"), CardsFactory.builder("888").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("77778888000ccc"), CardsFactory.builder("888").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("77778888000CCC"), CardsFactory.builder("888").list.get(0)));
        System.out.println("----------------------------------炸弹----------------------------------");
        System.out.println("----------------------------------三带一----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("555666c"), CardsFactory.builder("4441").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("CCC6"), CardsFactory.builder("4441").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("33334444555666777"), CardsFactory.builder("4441").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("333456cccCCC777"), CardsFactory.builder("4441").list.get(0)));
        System.out.println("----------------------------------三带一对----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("555666cC"), CardsFactory.builder("44411").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("33334444555666777"), CardsFactory.builder("44422").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("333445566cccCCC777"), CardsFactory.builder("444133").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("333445566cccCCC777"), CardsFactory.builder("4441CC").list.get(0)));
        System.out.println("----------------------------------四带二----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("44446666"), CardsFactory.builder("555512").list.get(0)));
        System.out.println("----------------------------------四带两队----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("444455556666"), CardsFactory.builder("33334444").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("4444455556666"), CardsFactory.builder("33334444").list.get(0)));//TODO
        System.out.println("----------------------------------顺子----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA2cC"), CardsFactory.builder("34567").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA2cC"), CardsFactory.builder("345678").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA2cC"), CardsFactory.builder("3456789").list.get(0)));
        System.out.println("----------------------------------连对----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA234567890JQKA2cC"), CardsFactory.builder("334455").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA234567890JQKA2cC"), CardsFactory.builder("33445566").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA234567890JQKA2cC"), CardsFactory.builder("3344556677").list.get(0)));
        System.out.println("----------------------------------飞机----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA234567890JQKA234567890JQKA2cC"), CardsFactory.builder("333444").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA234567890JQKA234567890JQKA2cC"), CardsFactory.builder("333444555").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA234567890JQKA234567890JQKA2cC"), CardsFactory.builder("333444555666").list.get(0)));
        System.out.println("----------------------------------飞机带单牌----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("44455566678"), CardsFactory.builder("44433365").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("444555666"), CardsFactory.builder("33344456").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("333444666777888"), CardsFactory.builder("33344456").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("4444555666789"), CardsFactory.builder("33344456").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("4445556666"), CardsFactory.builder("33344456").list.get(0)));
        System.out.println("----------------------------------飞机带对子----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("777666Cc3344"), CardsFactory.builder("3334445566").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA234567890JQKA234567890JQKA2cC"), CardsFactory.builder("3334445566").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA234567890JQKA234567890JQKA2cC"), CardsFactory.builder("333444555112244").list.get(0)));
        System.out.println(new Prompt(CardUtils.CreateCards("34567890JQKA234567890JQKA234567890JQKA2cC"), CardsFactory.builder("33344455566611227788").list.get(0)));
        System.out.println("----------------------------------NULL----------------------------------");
        System.out.println(new Prompt(CardUtils.CreateCards("66778"), CardProduct.createNullType()));
    }

    public static void main(String[] args) {
        typeTest();
        outCardTest();
        prompt();
    }
}
